// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Authentication struct {
	User         *User     `json:"user"`
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiredAt    time.Time `json:"expiredAt"`
}

type Coordinate struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type GetMachineByCodeInput struct {
	Area int `json:"area"`
}

type GetMachineByRegionInput struct {
	Region string `json:"region"`
}

type Location struct {
	Name       string      `json:"name"`
	URL        string      `json:"url"`
	Area       int         `json:"area"`
	Coordinate *Coordinate `json:"coordinate"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Machine struct {
	Name       string      `json:"name"`
	Location   string      `json:"location"`
	City       string      `json:"city"`
	Designs    string      `json:"designs"`
	Updated    time.Time   `json:"updated"`
	Area       int         `json:"area"`
	Region     string      `json:"region"`
	Coordinate *Coordinate `json:"coordinate,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
