// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Authentication struct {
	User         *User     `json:"user"`
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiredAt    time.Time `json:"expiredAt"`
}

type GetMachineByCodeInput struct {
	Area int `json:"area"`
}

type GetMachineByRegionInput struct {
	Region string `json:"region"`
}

type Location struct {
	Name string `json:"name"`
	URL  string `json:"url"`
	Area int    `json:"area"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Machine struct {
	Name     string    `json:"name"`
	Location string    `json:"location"`
	City     string    `json:"city"`
	Designs  string    `json:"designs"`
	Updated  time.Time `json:"updated"`
}

type User struct {
	Name string `json:"name"`
}
